// Command ortgen compiles internal/ortgen/dump_offsets.c against a
// pinned ONNX Runtime C header, runs it, and writes the resulting
// offsets and typed function declarations to a Go file. It is never
// imported by any package — it runs only via `go generate` (see
// ortcore/generate.go). It has no `import "C"` and requires no CGO to
// build; it only shells out to `cc` when *executed*.
package main

import (
	"bytes"
	_ "embed"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

//go:embed dump_offsets.c
var dumpOffsetsC string

func main() {
	headerDir := flag.String("header", os.Getenv("ORT_HEADER_DIR"),
		"directory containing onnxruntime_c_api.h (and the headers it includes) for the pinned ORT version")
	out := flag.String("out", "ortapi_gen.go", "output Go file path")
	flag.Parse()

	src, err := generate(*headerDir, dumpOffsetsC)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ortgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "ortgen: write", *out, ":", err)
		os.Exit(1)
	}
}

// generate compiles cSource against the headers in headerDir, runs the
// resulting binary, and returns gofmt-formatted Go source combining the
// generator's stdout with a package ortcore declaration. cSource is a
// parameter (rather than reading dumpOffsetsC directly) so tests can
// inject a deliberately broken C source to prove the safety net works.
func generate(headerDir, cSource string) ([]byte, error) {
	if headerDir == "" {
		return nil, fmt.Errorf("pass -header or set ORT_HEADER_DIR to the directory containing onnxruntime_c_api.h")
	}

	tmpDir, err := os.MkdirTemp("", "ortgen-*")
	if err != nil {
		return nil, fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	srcPath := filepath.Join(tmpDir, "dump_offsets.c")
	if err := os.WriteFile(srcPath, []byte(cSource), 0o644); err != nil {
		return nil, fmt.Errorf("write temp dump_offsets.c: %w", err)
	}

	binPath := filepath.Join(tmpDir, "dump_offsets")
	cc := exec.Command(ccCommand(), "-std=c11", "-Wall", "-Wextra", "-I", headerDir, srcPath, "-o", binPath)
	var ccErr bytes.Buffer
	cc.Stderr = &ccErr
	if err := cc.Run(); err != nil {
		return nil, fmt.Errorf("compile dump_offsets.c against %s: %w\n%s", headerDir, err, ccErr.String())
	}

	stdout, err := exec.Command(binPath).Output()
	if err != nil {
		var exitErr *exec.ExitError
		if errors.As(err, &exitErr) {
			return nil, fmt.Errorf("run dump_offsets: %w\n%s", err, exitErr.Stderr)
		}
		return nil, fmt.Errorf("run dump_offsets: %w", err)
	}

	// ORT 1.28.0 pinned in ARQUITETURA_OFICIAL.md §6.7. Update this
	// alongside the pinned version if it ever changes — the header does
	// not expose a full semver macro (only ORT_API_VERSION, the minor
	// version number, per §2.6.6), so it can't be derived automatically.
	header := "// Code generated by internal/ortgen from onnxruntime_c_api.h v1.28.0. DO NOT EDIT.\n\npackage ortcore\n\n"
	full := append([]byte(header), stdout...)

	formatted, err := format.Source(full)
	if err != nil {
		return nil, fmt.Errorf("generator output is not valid Go: %w\n---\n%s", err, full)
	}

	if err := checkGoSignatureArity(string(formatted)); err != nil {
		return nil, fmt.Errorf("Go type declaration disagrees with its C signature: %w", err)
	}

	return formatted, nil
}

// ccCommand returns the C compiler to invoke: $CC if set, "cc"
// otherwise. The generator requires a GCC- or Clang-compatible
// compiler — dump_offsets.c relies on __typeof__ and
// __builtin_types_compatible_p, non-standard C11 extensions not
// available in e.g. MSVC.
func ccCommand() string {
	if cc := os.Getenv("CC"); cc != "" {
		return cc
	}
	return "cc"
}

// checkGoSignatureArity is the Go-side half of the signature check
// described in ARQUITETURA_OFICIAL.md §6.1. dump_offsets.c's CHECK macro
// already proves, at C-compile time, that each function's declared C
// signature (CSIG) matches the real OrtApi field. But the Go type
// (GOSIG) is typed by hand in dump_offsets.c and nothing previously
// verified it against CSIG — a GOSIG with a dropped parameter compiled
// and generated silently.
//
// dump_offsets.c's PRINT_TYPE macro now emits a "// C: <signature>"
// comment immediately above each generated `type fnX func(...)` line.
// This walks the formatted source looking for that comment/declaration
// pairing and compares parameter counts. It intentionally does not
// compare types — that's still the C compiler's job for CSIG, and the
// Go compiler's job once the wrapper is used — just arity, which is
// enough to catch a dropped or added parameter like the one the review
// used to demonstrate the hole.
//
// It also guards against a subtler regression than a wrong signature:
// a missing one. Every "type fnX" declaration in src must be preceded
// by a "// C: " comment — if dump_offsets.c's PRINT_TYPE macro ever
// stops emitting that comment (for any entry, including the two
// OrtApiBase types outside the ORT_FUNCTIONS X-macro), the loop below
// would simply find nothing to check for that entry and return nil,
// silently reopening the exact hole this function exists to close.
// Counting declarations against checked pairs turns that into a loud
// failure instead (ARQUITETURA_OFICIAL.md §6.8, item 1).
func checkGoSignatureArity(src string) error {
	wantChecks := strings.Count(src, "\ntype fn")
	checked := 0

	lines := strings.Split(src, "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		cSig, ok := strings.CutPrefix(trimmed, "// C: ")
		if !ok {
			continue
		}
		if i+1 >= len(lines) {
			return fmt.Errorf("dangling %q comment with no following type declaration", trimmed)
		}
		typeLine := strings.TrimSpace(lines[i+1])

		name, goArity, err := goFuncTypeArity(typeLine)
		if err != nil {
			return fmt.Errorf("parsing Go type declaration following %q: %w", trimmed, err)
		}

		cArity, err := cSignatureArity(cSig)
		if err != nil {
			return fmt.Errorf("%s: parsing C signature %q: %w", name, cSig, err)
		}

		if cArity != goArity {
			return fmt.Errorf("%s: C signature has %d parameter(s) but the generated Go type has %d — C=%q Go=%q",
				name, cArity, goArity, cSig, typeLine)
		}
		checked++
	}

	if checked != wantChecks {
		return fmt.Errorf("%d generated type declaration(s) but only %d were paired with a \"// C: \" signature comment — every generated type must be arity-checked, none may be silently unguarded", wantChecks, checked)
	}
	return nil
}

// goFuncTypeArity parses a single "type fnX func(...) ..." declaration
// and returns the function name (fnX) and its parameter count.
func goFuncTypeArity(typeLine string) (name string, arity int, err error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "", "package p\n"+typeLine+"\n", 0)
	if err != nil {
		return "", 0, fmt.Errorf("not valid Go: %w", err)
	}
	if len(f.Decls) != 1 {
		return "", 0, fmt.Errorf("expected exactly one declaration, got %d", len(f.Decls))
	}
	gd, ok := f.Decls[0].(*ast.GenDecl)
	if !ok || gd.Tok != token.TYPE || len(gd.Specs) != 1 {
		return "", 0, fmt.Errorf("expected a single type declaration")
	}
	ts, ok := gd.Specs[0].(*ast.TypeSpec)
	if !ok {
		return "", 0, fmt.Errorf("expected a type spec")
	}
	ft, ok := ts.Type.(*ast.FuncType)
	if !ok {
		return "", 0, fmt.Errorf("expected a func type")
	}
	if ft.Params != nil {
		for _, field := range ft.Params.List {
			n := len(field.Names)
			if n == 0 {
				n = 1
			}
			arity += n
		}
	}
	return ts.Name.Name, arity, nil
}

// cSignatureArity counts the parameters of a C function-pointer-type
// signature such as `OrtStatus*(*)(OrtLoggingLevel, const char*,
// OrtEnv**)`. It finds the last top-level parenthesized group (the
// parameter list — the earlier `(*)` is the function-pointer marker, not
// a parameter list) and counts its top-level commas, handling `(void)`
// and a single parameter with no comma.
func cSignatureArity(sig string) (int, error) {
	sig = strings.TrimSpace(sig)
	if !strings.HasSuffix(sig, ")") {
		return 0, fmt.Errorf("does not end in ')'")
	}

	depth := 0
	start := -1
	for i := len(sig) - 1; i >= 0; i-- {
		switch sig[i] {
		case ')':
			depth++
		case '(':
			depth--
			if depth == 0 {
				start = i
			}
		}
		if start != -1 {
			break
		}
	}
	if start == -1 {
		return 0, fmt.Errorf("unbalanced parentheses")
	}

	inner := strings.TrimSpace(sig[start+1 : len(sig)-1])
	if inner == "" || inner == "void" {
		return 0, nil
	}

	count := 1
	parenDepth := 0
	for _, r := range inner {
		switch r {
		case '(':
			parenDepth++
		case ')':
			parenDepth--
		case ',':
			if parenDepth == 0 {
				count++
			}
		}
	}
	return count, nil
}
