// Command ortgen compiles internal/ortgen/dump_offsets.c against a
// pinned ONNX Runtime C header, runs it, and writes the resulting
// offsets and typed function declarations to a Go file. It is never
// imported by any package — it runs only via `go generate` (see
// ortcore/generate.go). It has no `import "C"` and requires no CGO to
// build; it only shells out to `cc` when *executed*.
package main

import (
	"bytes"
	_ "embed"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
)

//go:embed dump_offsets.c
var dumpOffsetsC string

func main() {
	headerDir := flag.String("header", os.Getenv("ORT_HEADER_DIR"),
		"directory containing onnxruntime_c_api.h (and the headers it includes) for the pinned ORT version")
	out := flag.String("out", "ortapi_gen.go", "output Go file path")
	flag.Parse()

	src, err := generate(*headerDir, dumpOffsetsC)
	if err != nil {
		fmt.Fprintln(os.Stderr, "ortgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "ortgen: write", *out, ":", err)
		os.Exit(1)
	}
}

// generate compiles cSource against the headers in headerDir, runs the
// resulting binary, and returns gofmt-formatted Go source combining the
// generator's stdout with a package ortcore declaration. cSource is a
// parameter (rather than reading dumpOffsetsC directly) so tests can
// inject a deliberately broken C source to prove the safety net works.
func generate(headerDir, cSource string) ([]byte, error) {
	if headerDir == "" {
		return nil, fmt.Errorf("pass -header or set ORT_HEADER_DIR to the directory containing onnxruntime_c_api.h")
	}

	tmpDir, err := os.MkdirTemp("", "ortgen-*")
	if err != nil {
		return nil, fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tmpDir)

	srcPath := filepath.Join(tmpDir, "dump_offsets.c")
	if err := os.WriteFile(srcPath, []byte(cSource), 0o644); err != nil {
		return nil, fmt.Errorf("write temp dump_offsets.c: %w", err)
	}

	binPath := filepath.Join(tmpDir, "dump_offsets")
	cc := exec.Command("cc", "-std=c11", "-Wall", "-Wextra", "-I", headerDir, srcPath, "-o", binPath)
	var ccErr bytes.Buffer
	cc.Stderr = &ccErr
	if err := cc.Run(); err != nil {
		return nil, fmt.Errorf("compile dump_offsets.c against %s:\n%s", headerDir, ccErr.String())
	}

	stdout, err := exec.Command(binPath).Output()
	if err != nil {
		return nil, fmt.Errorf("run dump_offsets: %w", err)
	}

	header := "// Code generated by internal/ortgen from onnxruntime_c_api.h. DO NOT EDIT.\n\npackage ortcore\n\n"
	full := append([]byte(header), stdout...)

	formatted, err := format.Source(full)
	if err != nil {
		return nil, fmt.Errorf("generator output is not valid Go: %w\n---\n%s", err, full)
	}
	return formatted, nil
}
