// Code generated by internal/ortgen from onnxruntime_c_api.h. DO NOT EDIT.

package ortcore

const ortAPIVersion = 28

const offBaseGetApi = 0
const offBaseGetVersionString = 8
const offCreateEnv = 24
const offCreateSessionOptions = 80
const offCreateSession = 56
const offRun = 72
const offGetErrorCode = 8
const offGetErrorMessage = 16
const offReleaseStatus = 744
const offCreateCpuMemoryInfo = 552
const offCreateTensorWithDataAsOrtValue = 392
const offGetTensorMutableData = 408
const offGetTensorTypeAndShape = 520
const offGetDimensionsCount = 488
const offGetDimensions = 496
const offSessionGetInputCount = 240
const offSessionGetOutputCount = 248
const offSessionGetInputName = 288
const offSessionGetOutputName = 296
const offAllocatorFree = 608
const offGetAllocatorWithDefaultOptions = 624
const offReleaseEnv = 736
const offReleaseSession = 760
const offReleaseSessionOptions = 800
const offReleaseValue = 768
const offReleaseMemoryInfo = 752
const offReleaseTensorTypeAndShapeInfo = 792

type fnGetApi func(version uint32) uintptr
type fnGetVersionString func() uintptr
type fnCreateEnv func(logSeverityLevel int32, logid uintptr, out *uintptr) uintptr
type fnCreateSessionOptions func(out *uintptr) uintptr
type fnCreateSession func(env uintptr, modelPath uintptr, options uintptr, out *uintptr) uintptr
type fnRun func(session uintptr, runOptions uintptr, inputNames uintptr, inputs uintptr, inputLen uintptr, outputNames uintptr, outputNamesLen uintptr, outputs uintptr) uintptr
type fnGetErrorCode func(status uintptr) int32
type fnGetErrorMessage func(status uintptr) uintptr
type fnReleaseStatus func(input uintptr)
type fnCreateCpuMemoryInfo func(typ int32, memType int32, out *uintptr) uintptr
type fnCreateTensorWithDataAsOrtValue func(info uintptr, pData uintptr, pDataLen uintptr, shape uintptr, shapeLen uintptr, typ int32, out *uintptr) uintptr
type fnGetTensorMutableData func(value uintptr, out *uintptr) uintptr
type fnGetTensorTypeAndShape func(value uintptr, out *uintptr) uintptr
type fnGetDimensionsCount func(info uintptr, out *uintptr) uintptr
type fnGetDimensions func(info uintptr, dimValues uintptr, dimValuesLength uintptr) uintptr
type fnSessionGetInputCount func(session uintptr, out *uintptr) uintptr
type fnSessionGetOutputCount func(session uintptr, out *uintptr) uintptr
type fnSessionGetInputName func(session uintptr, index uintptr, allocator uintptr, value *uintptr) uintptr
type fnSessionGetOutputName func(session uintptr, index uintptr, allocator uintptr, value *uintptr) uintptr
type fnAllocatorFree func(allocator uintptr, p uintptr) uintptr
type fnGetAllocatorWithDefaultOptions func(out *uintptr) uintptr
type fnReleaseEnv func(input uintptr)
type fnReleaseSession func(input uintptr)
type fnReleaseSessionOptions func(input uintptr)
type fnReleaseValue func(input uintptr)
type fnReleaseMemoryInfo func(input uintptr)
type fnReleaseTensorTypeAndShapeInfo func(input uintptr)
