// Code generated by internal/ortgen from onnxruntime_c_api.h v1.28.0. DO NOT EDIT.

package ortcore

const ortAPIVersion = 28

const offBaseGetApi = 0
const offBaseGetVersionString = 8
const offCreateEnv = 24
const offCreateSessionOptions = 80
const offCreateSession = 56
const offRun = 72
const offGetErrorCode = 8
const offGetErrorMessage = 16
const offReleaseStatus = 744
const offCreateCpuMemoryInfo = 552
const offCreateTensorWithDataAsOrtValue = 392
const offGetTensorMutableData = 408
const offGetTensorTypeAndShape = 520
const offGetDimensionsCount = 488
const offGetDimensions = 496
const offSessionGetInputCount = 240
const offSessionGetOutputCount = 248
const offSessionGetInputName = 288
const offSessionGetOutputName = 296
const offAllocatorFree = 608
const offGetAllocatorWithDefaultOptions = 624
const offReleaseEnv = 736
const offReleaseSession = 760
const offReleaseSessionOptions = 800
const offReleaseValue = 768
const offReleaseMemoryInfo = 752
const offReleaseTensorTypeAndShapeInfo = 792

type fnGetApi func(version uint32) uintptr
type fnGetVersionString func() uintptr

// C: OrtStatus*(*)(OrtLoggingLevel, const char*, OrtEnv**)
type fnCreateEnv func(logSeverityLevel int32, logid uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(OrtSessionOptions**)
type fnCreateSessionOptions func(out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtEnv*, const ORTCHAR_T*, const OrtSessionOptions*, OrtSession**)
type fnCreateSession func(env uintptr, modelPath uintptr, options uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(OrtSession*, const OrtRunOptions*, const char* const*, const OrtValue* const*, size_t, const char* const*, size_t, OrtValue**)
type fnRun func(session uintptr, runOptions uintptr, inputNames uintptr, inputs uintptr, inputLen uintptr, outputNames uintptr, outputNamesLen uintptr, outputs uintptr) uintptr

// C: OrtErrorCode(*)(const OrtStatus*)
type fnGetErrorCode func(status uintptr) int32

// C: const char*(*)(const OrtStatus*)
type fnGetErrorMessage func(status uintptr) uintptr

// C: void(*)(OrtStatus*)
type fnReleaseStatus func(input uintptr)

// C: OrtStatus*(*)(OrtAllocatorType, OrtMemType, OrtMemoryInfo**)
type fnCreateCpuMemoryInfo func(typ int32, memType int32, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtMemoryInfo*, void*, size_t, const int64_t*, size_t, ONNXTensorElementDataType, OrtValue**)
type fnCreateTensorWithDataAsOrtValue func(info uintptr, pData uintptr, pDataLen uintptr, shape uintptr, shapeLen uintptr, typ int32, out *uintptr) uintptr

// C: OrtStatus*(*)(OrtValue*, void**)
type fnGetTensorMutableData func(value uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtValue*, OrtTensorTypeAndShapeInfo**)
type fnGetTensorTypeAndShape func(value uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtTensorTypeAndShapeInfo*, size_t*)
type fnGetDimensionsCount func(info uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtTensorTypeAndShapeInfo*, int64_t*, size_t)
type fnGetDimensions func(info uintptr, dimValues uintptr, dimValuesLength uintptr) uintptr

// C: OrtStatus*(*)(const OrtSession*, size_t*)
type fnSessionGetInputCount func(session uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtSession*, size_t*)
type fnSessionGetOutputCount func(session uintptr, out *uintptr) uintptr

// C: OrtStatus*(*)(const OrtSession*, size_t, OrtAllocator*, char**)
type fnSessionGetInputName func(session uintptr, index uintptr, allocator uintptr, value *uintptr) uintptr

// C: OrtStatus*(*)(const OrtSession*, size_t, OrtAllocator*, char**)
type fnSessionGetOutputName func(session uintptr, index uintptr, allocator uintptr, value *uintptr) uintptr

// C: OrtStatus*(*)(OrtAllocator*, void*)
type fnAllocatorFree func(allocator uintptr, p uintptr) uintptr

// C: OrtStatus*(*)(OrtAllocator**)
type fnGetAllocatorWithDefaultOptions func(out *uintptr) uintptr

// C: void(*)(OrtEnv*)
type fnReleaseEnv func(input uintptr)

// C: void(*)(OrtSession*)
type fnReleaseSession func(input uintptr)

// C: void(*)(OrtSessionOptions*)
type fnReleaseSessionOptions func(input uintptr)

// C: void(*)(OrtValue*)
type fnReleaseValue func(input uintptr)

// C: void(*)(OrtMemoryInfo*)
type fnReleaseMemoryInfo func(input uintptr)

// C: void(*)(OrtTensorTypeAndShapeInfo*)
type fnReleaseTensorTypeAndShapeInfo func(input uintptr)
